version: '3'
services:
    habrabot:
        build:
            context: .
        image: habrabot
        restart: always
        env_file: ./.env
        environment:
            BOLTDB_PATH: /data/boltdb.dat
        volumes:
          - ./data/:/data
