version: '3'
services:
    habrabot:
        image: habrabot
        build:
            context: .
        env_file: ./.env
        volumes:
          - ./data/:/data
        environment:
            RSS_DB_PATH: /data/rss.dat
        restart: always
